name: Backend CI/CD Pipeline
on:
  push:
    paths:
      - 'CafeManagement/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'CafeManagement/**'
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      working-directory: ./CafeManagement
      run: dotnet restore Cafe.API/Cafe.API.csproj
      
    - name: Build
      working-directory: ./CafeManagement
      run: dotnet build Cafe.API/Cafe.API.csproj --no-restore --configuration Release
      
    - name: Test
      working-directory: ./CafeManagement
      run: dotnet test Cafe.Application.Test/Cafe.Application.Test.csproj --configuration Release
      
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./CafeManagement
        file: ./CafeManagement/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/cafe-api:latest